### ISSUE TITLE
Adding fields in the Agro dealer form

### ISSUE THREAD

**Issue by 8technologies** [8technologies/stts-sahel-web#2]
In this form, i see District, circle, but hear in Niger, we talk about Région, Département, Commune, Village/quartier. We should add another field for telephone number. It seems too that this form is for Retailers, i didn't see for wholesalers. Thanks;

Directions
- at the top of the form, add a raadio button called agro dealer category, with two options , reatilers and wholesalers
- Add the new fields in the agro dealers table, remove the ones they dont want, edit the migration and model too ,
- Add the translations for the new field in the lang files for fr and en
- Check the apis too
- Test

**Comment by PriscillaCole** [comment]
Well done
